### ISSUE TITLE
Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint

### ISSUE THREAD

**Issue by waynehoover** [julianfssen/tweetkit#13]
getting:

`Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint`

when calling the post_tweet method. What can I do to fix this? My credentials are all correct.

**Comment by abeger** [comment]
So, the instructions in the README do not work for posting tweets. If you supply a bearer token, you end up connecting using Application-Only auth, [which is read-only](https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only).

You need to log in with the full complement of keys here:

```ruby
client = Tweetkit::Client.new do |config|
  config.consumer_key = CONSUMER_KEY
  config.consumer_secret = CONSUMER_KEY_SECRET
  config.access_token = ACCESS_TOKEN
  config.access_token_secret = ACCESS_TOKEN_SECRET
end
```

For reference, you can see the connection code here: https://github.com/julianfssen/tweetkit/blob/master/lib/tweetkit/connection.rb#L37

**Comment by waynehoover** [comment]
Thank you, that does it.
