### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghosteathuman** [julianfssen/tweetkit#2]
Interesting gem you have here 😉

I am wondering if you will be adding an explicit license to this project?

**Comment by julianfssen** [comment]
Hey @ghosteathuman ! Thanks for bringing this up. I completely forgot about it while editing the README, and I will update it in the next merge. I'll be using the standard MIT license for this. 

Anyways, thanks for reminding me and do let me know if you have any other feedback regarding the gem. Thanks again! :)
