### ISSUE TITLE
Please push latest version with #post_tweets to RubyGems

### ISSUE THREAD

**Issue by samuel-henry** [julianfssen/tweetkit#9]
Thanks for the great work!

The latest version is July 16, 2021 

Thank you!

**Comment by julianfssen** [comment]
Thanks for the reminder @samuel-henry ! I have created a release with the latest commits in the past months. Thanks again for your support :)

**Comment by samuel-henry** [comment]
Thank you @julianfssen !

Unfortunately I'm getting an error updating to the latest version:

`
$  gem install tweetkit
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between faraday-net_http and faraday

$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
`

**Comment by samuel-henry** [comment]
Looks related to https://github.com/lostisland/faraday/issues/1369
